import Head from 'next/head'
import Image from 'next/image'
import ThreeDCard from '../components/ui/ThreeDCard'
import styles from '../styles/Home.module.css'
import { motion as m, AnimatePresence } from 'framer-motion';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* Google Tag Manager */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=AW-16654642441"></script>
        <script dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-16654642441');
          `,
        }} />
        {/* End Google Tag Manager */}
      </Head>

      <main className={styles.main}>
        {/* <ThreeDCard>
          <h1 className="font-bold text-3xl">
            eightynine
          </h1>
        </ThreeDCard> */}
        <AnimatePresence>
          <m.div 
            className="relative flex justify-center items-center"
          >
            <m.h1 
              className="absolute font-bold text-5xl z-10 dark:text-slate-50 text-slate-800"
              initial={{ opacity: 0, y: 100}}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              transition={{ 
                duration: 0.5, ease: "easeIn",
                opacity: { duration: 1.2 } 
              }}
            >
              eightynine
            </m.h1>
            <m.span 
              className="absolute font-bold text-[200px] dark:text-slate-800 text-slate-200"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{
                opacity: { duration: 0.7 }
              }}
            >
              89
            </m.span>
          </m.div>
        </AnimatePresence>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by me
        </a>
      </footer>
    </div>
  )
}
